### ISSUE TITLE
Custom Dataset Question

### ISSUE THREAD

**Issue by impulsecorp** [idstcv/ZenNAS#22]
I want to use ZenNAS on a medical image dataset, but am confused when you say ZenNAS is "data-free" and "a data independent method. " I understand how it is "training-free", and that the calculation of Zen-Score only takes a few forward inferences through a randomly initialized network, but is this zero-shot Zen-Score based at all on my data?

**Comment by MingLin-home** [comment]
Hi impulsecorp,

Thank you for your good question! 

Zen-score uses random input (Gaussioan signal) so it does not read any data in your training set. Even if you use real data as input, the result would be of no difference because the network parameters are random Gaussian, i.e., the output of the stem layer is random Gaussian.

BTW, you might be interested in our follow-up work:
[MAE-DET: Revisiting Maximum Entropy Principle in Zero-Shot NAS for Efficient Object Detection](https://arxiv.org/abs/2111.13336). The source code is [here](https://github.com/alibaba/lightweight-neural-architecture-search).
