### ISSUE TITLE
Same search space used in search_space_IDW_fixfc.py as well as in search_space_XXBL.py

### ISSUE THREAD

**Issue by soyebn** [idstcv/ZenNAS#5]
First of all, thanks a lot for releasing the code for such a nice work. I have few doubts,

1) The **seach_space_block_type_list_list** in both files, _search_space_IDW_fixfc.py_ as well as _search_space_XXBL.py_ are same. Is it intended?

2) The script, _Zen_NAS_ImageNet_flops400M.sh_  and _Zen_NAS_ImageNet_latency0.2ms_ use same search space. But the paper mentions _Zen_NAS_ImageNet_flops400M.sh_ using **MB** block and  _Zen_NAS_ImageNet_latency0.2ms_ uses **botn** block like **Resnet50**.

Thanks again.

**Comment by MingLin-home** [comment]
Dear Soyeb,

Thanks for the feedback and sorry for the bugs. The file XXBL is not copied correctly from our original big code base. There are also several debug code files I forgot to delete. These have been fixed in the updated version.

Please let me know if you encounter any more issues. We will fix them as soon as possible.

Best Regards,
Ming Lin

**Comment by soyebn** [comment]
Thanks. New code looks fine now, except for the few small things.
1.  --_use_se_ is missing from **Zen_NAS_ImageNet_flops400M.sh** and **Zen_NAS_ImageNet_flops600M.sh**
2. Pre-trained weights missing, https://idstcv.oss-cn-zhangjiakou.aliyuncs.com/pretrained_models/iccv2021_zennet_imagenet1k_flops400M_SE_res224/student_best-params_rank0.pth

Thanks again for the quick response. I have another question about multi GPU training for which I will raise another issue and close this.

**Comment by MingLin-home** [comment]
Dear Soyeb,

Couldn't appreciate you more!

I have fixed the bug you found above.  About the pre-trained weight, I have
fixed the url.
